kind: Deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app.oscro.io/name: accountserver
  template:
    spec:
      volumes:
        - name: accountserver-cm
          configMap:
            name: accountserver-cm
        - name: accountserver-persistentvolumeclaim-pvc
          persistentVolumeClaim:
            claimName: accountserver-persistentvolumeclaim-pvc
      containers:
        - name: accountserver
          image: octahub.8lab.cn:5000/oscro/accountserver:v2309201614
          # image: octahub.8lab.cn:5000/oscro/octa-accountserver-2.2-t:2309041630
          resources:
            limits:
              cpu: 100m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 500Mi
          volumeMounts:
            - name: accountserver-cm
              subPath: conf.json
              mountPath: /usr/local/server/src/config/conf.json
            - name: accountserver-persistentvolumeclaim-pvc
              mountPath: /data/oscro-v2/logs
      imagePullSecrets:
        - name: registry-secret
    metadata:
      labels:
        app.oscro.io/name: accountserver
metadata:
  name: accountserver-deployment-deploy
  labels:
    app.oscro.io/name: accountserver
  namespace: oscro-v2
apiVersion: apps/v1
