data:
  config.ini: |
    [service]
    Mode = release 
    Port = 10085
    Address = 192.168.1.96
    Name = harborServer

    [mysql]
    Db = mysql
    DbAddress = 192.168.1.99
    DbPort = 3306
    DbUser = 8lab
    DbPassWord = 8lab
    DbName = oscro
    Charset = utf8mb4

    [consul]
    Address = 192.168.1.97
    Port = 8500
    Token = b408de14-17e3-216a-cd74-124a6a3914de
    NodeSide = 3 

    [log]
    Path = /data/oscro-v2/logs
    SaveDay = 7

    [nsq]
    NsqD = nsqd-service-svc.oscro-v2:4150
    NsqLookupD = nsqlookupd-service-svc.oscro-v2:4161
    HarborProjectCreate = 180E99EB-819A-D6B8-6B73-F68F58DA9ADF
    HarborProjectDelete = C3840C38-D3A1-2BAD-9D42-C52288ADFC6A
    HarborCreate = AAB41771-4C8C-2339-CA3A-7FF05077DF7C
    MdHarborProjectCreate = F067B691-173B-107F-C337-CC69B10CE040
    SyncImage = 196E169F-287F-AEAC-59BB-DCAEEE0126CA

    [md_hb]
    Name = md_harbor
    Schema = http
    Domain = octa8lab.hub.cn
    Address = 103.210.160.242
    Port = 5000
    Username = admin
    Password = 7zUdZszglt

kind: ConfigMap
metadata:
  name: harborserver-cm
  labels:
    app.oscro.io/name: harborserver
  namespace: oscro-v2
apiVersion: v1
