---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ceph-osd
spec:
  selector:
    matchLabels:
      app: osd
  template:
    metadata:
      labels:
        app: osd
    spec:
      imagePullSecrets:
      - name: registry-secret
      initContainers:
      - name: chmod
        image: octahub.8lab.cn:5000/99/busybox:1.28
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        command: ["sh", "-c", "chown -R 1000:1000 /data/ceph/osd"]
        volumeMounts:
          - name: osd-key
            mountPath: /data/ceph/osd
      containers:
      - image: octahub.8lab.cn:5000/99/ceph-osd:v220418
        imagePullPolicy: IfNotPresent
        name: ceph-osd
        securityContext:
          privileged: true
        env:
          - name: OSD_DEV
            #value: /dev/sdb1
            value: /dev/sda1
        volumeMounts:
          - mountPath: /etc/ceph/ceph.conf
            subPath: ceph.conf
            name: ceph-config
#          - mountPath: /etc/ceph/ceph.mon.keyring
#            subPath: ceph.mon.keyring
#            name: ceph-mon-keyring
#          - mountPath: /etc/ceph/ceph.client.admin.keyring
#            subPath: ceph.client.admin.keyring
#            name: client-admin-keyring
          - mountPath: /var/lib/ceph/osd/
            name: osd-key
      volumes:
      - name: ceph-config
        configMap:
          name: ceph-configmap
      - name: osd-key
        hostPath:
          path: /data/ceph/osd
#      - name: client-admin-keyring
#        secret:
#          secretName: client-admin-keyring
#      - name: ceph-mon-keyring
#        secret:
#          secretName: ceph-mon-keyring
      hostNetwork: true
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: ceph-osd
                operator: In
                values:
                - enabled
