kind: ConfigMap
apiVersion: v1
metadata:
  name: ck-keeper-cm
  namespace: appdata
data:
  config.xml: |
    <clickhouse>
        <logger>
            <!-- Possible levels [1]:
              - none (turns off logging)
              - fatal
              - critical
              - error
              - warning
              - notice
              - information
              - debug
              - trace
                [1]: https://github.com/pocoproject/poco/blob/poco-1.9.4-release/Foundation/include/Poco/Logger.h#L105-L114
            -->
            <level>information</level>
            <console>true</console>
            <size>100M</size>
            <count>5</count>
        </logger>
        <max_connections>4096</max_connections>
        <listen_host>0.0.0.0</listen_host>
        <keeper_server>
                <tcp_port>9181</tcp_port>
                <!-- Must be unique among all keeper serves -->
                <server_id>1</server_id>
                <four_letter_word_white_list>*</four_letter_word_white_list>
                <log_storage_path>/usr/local/clickhouse-keeper/logs</log_storage_path>
                <snapshot_storage_path>/usr/local/clickhouse-keeper/snapshots</snapshot_storage_path>
    
                <coordination_settings>
                    <operation_timeout_ms>10000</operation_timeout_ms>
                    <min_session_timeout_ms>10000</min_session_timeout_ms>
                    <session_timeout_ms>100000</session_timeout_ms>
                    <raft_logs_level>information</raft_logs_level>
                </coordination_settings>
    
                <raft_configuration>
                    <server>
                        <id>1</id>
                        <hostname>ck-keeper-sts-0.ck-keeper-svc.appdata.svc.cluster.local</hostname>
                        <port>9234</port>
                    </server>
                    <server>
                        <id>2</id>
                        <hostname>ck-keeper-sts-1.ck-keeper-svc.appdata.svc.cluster.local</hostname>
                        <port>9234</port>
                    </server>
                    <server>
                        <id>3</id>
                        <hostname>ck-keeper-sts-2.ck-keeper-svc.appdata.svc.cluster.local</hostname>
                        <port>9234</port>
                    </server>
                </raft_configuration>
        </keeper_server>
    </clickhouse>
