apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ck-keeper-sts
  namespace: appdata
spec:
  selector:
    matchLabels:
      app: ck-keeper
  serviceName: ck-keeper-svc
  replicas: 3
  template:
    metadata:
      labels:
        app: ck-keeper
    spec:
      imagePullSecrets:
      - name: registry-secret
      initContainers:
#     - name: init-ulimit
#       image: octahub.8lab.cn:5000/99/busybox:1.28
#       imagePullPolicy: IfNotPresent
#       securityContext:
#         privileged: true
#       command: ["sh", "-c", "ulimit -n 655350"]
      - name: init-chown
        image: octahub.8lab.cn:5000/99/busybox:1.28
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        command: ["sh", "-c", "chown -R 1000. /usr/local/clickhouse-keeper"]
        volumeMounts:
        - name: ck-keeper-data
          mountPath: /usr/local/clickhouse-keeper
      containers:
      - name: clickhouse
       #image: octahub.8lab.cn:5000/99/clickhouse-keeper:v22.12.6
       #image: octahub.8lab.cn:5000/99/clickhouse-keeper:v23.3.7
        image: octahub.8lab.cn:5000/99/clickhouse-keeper:v23.5.4
       #command:
       #- sh
       #- -c
       #args:
       #- sleep infinity
        imagePullPolicy: Always
        ports:
        - containerPort: 9000
        volumeMounts:
        - name: ck-keeper-cm
          mountPath: /etc/clickhouse-keeper/config.xml
          subPath: config.xml
        - name: ck-keeper-data
          mountPath: /usr/local/clickhouse-keeper
      volumes:
      - name: ck-keeper-cm
        configMap:
          name: ck-keeper-cm
  volumeClaimTemplates:
  - metadata:
      name: ck-keeper-data
    spec:
      storageClassName: "csi-rbd-sc"
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
