---
apiVersion: v1
kind: Service
metadata:
  name: ck-keeper-svc
  namespace: appdata
spec:
  ports:
  - port: 9181
    targetPort: 9181
    name: ck-keeper
  - port: 9234
    targetPort: 9234
    name: ck-keeper-raft
  selector:
    app: ck-keeper
