kind: StatefulSet
spec:
  replicas: 3
  selector:
    matchLabels:
      app.oscro.io/name: consul-server
  template:
    spec:
      volumes:
        - name: consul-server-configmap-acl
          configMap:
            name: consul-server-configmap-acl
      containers:
        - env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          args:
            - agent
            - '-server'
            - '-config-dir=/usr/local/consul/config'
            - '-bootstrap-expect=3'
            - '-data-dir=/data/consul'
            - '-bind=0.0.0.0'
            - '-client=0.0.0.0'
            - '-advertise=$(POD_IP)'
            - >-
              -retry-join=consul-server-statefulset-sts-0.consul-server-service-svc.$(NAMESPACE).svc.cluster.local
            - >-
              -retry-join=consul-server-statefulset-sts-1.consul-server-service-svc.$(NAMESPACE).svc.cluster.local
            - >-
              -retry-join=consul-server-statefulset-sts-2.consul-server-service-svc.$(NAMESPACE).svc.cluster.local
            - '-domain=cluster.local'
            - '-disable-host-node-id'
          name: consul
          image: octahub.8lab.cn:5000/99/consul:v1.15.2
          ports:
            - name: http
              containerPort: 8500
            - name: rpc
              containerPort: 8400
            - name: https-port
              containerPort: 8443
            - name: serf-lan
              containerPort: 8301
            - name: serf-wan
              containerPort: 8302
            - name: consul-dns
              containerPort: 8600
            - name: server
              containerPort: 8300
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 200m
              memory: 200Mi
          volumeMounts:
            - name: consul-data
              mountPath: /data/consul
            - name: consul-server-configmap-acl
              mountPath: /usr/local/consul/config
          imagePullPolicy: Always
      imagePullSecrets:
        - name: registry-secret
      terminationGracePeriodSeconds: 10
    metadata:
      labels:
        app.oscro.io/name: consul-server
  serviceName: consul-server-service-svc
  volumeClaimTemplates:
    - spec:
        resources:
          requests:
            storage: 5Gi
        accessModes:
          - ReadWriteOnce
      metadata:
        name: consul-data
        annotations:
          volume.beta.kubernetes.io/storage-class: csi-rbd-sc
metadata:
  name: consul-server-statefulset-sts
  labels:
    app.oscro.io/name: consul-server
  namespace: oscro-v2
apiVersion: apps/v1
