kind: Service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8500
      protocol: TCP
      targetPort: 8500
    - name: https
      port: 8443
      protocol: TCP
      targetPort: 8443
    - name: rpc
      port: 8400
      protocol: TCP
      targetPort: 8400
    - name: serf-lan-tcp
      port: 8301
      protocol: TCP
      targetPort: 8301
    - name: serf-lan-udp
      port: 8301
      protocol: UDP
      targetPort: 8301
    - name: serf-wan-tcp
      port: 8302
      protocol: TCP
      targetPort: 8302
    - name: serf-wan-udp
      port: 8302
      protocol: UDP
      targetPort: 8302
    - name: server
      port: 8300
      protocol: TCP
      targetPort: 8300
    - name: consul-dns
      port: 8600
      protocol: TCP
      targetPort: 8600
  selector:
    app.oscro.io/name: consul-server
  externalIPs: []
metadata:
  name: consul-server-service-svc
  labels:
    app.oscro.io/name: consul-server
  namespace: oscro-v2
apiVersion: v1
