data:
  initpolicy.sh: >
    #!/bin/bash

    export CONSUL_HTTP_TOKEN=`grep -r initial /data/config/|awk -F'"' '{print
    $4}'`

    set -ux

    #创建策略

    consul acl policy create -name "node-r" -description "node read" -rules
    'node_prefix ""{policy = "read"}' &> /dev/null


    consul acl policy create -name "service-w" -description "service write"
    -rules 'service_prefix ""{policy = "write"}' &> /dev/null


    consul acl policy create -name "service-main-deny" -description "deny
    service_prefix main" -rules 'service_prefix "main"{policy = "deny"}' &>
    /dev/null


    #创建mainserver角色

    consul acl role create  -name "mainRegister" -description "mainServer role"
    -policy-name service-w -policy-name node-r &> /dev/null

    #创建只允许注册角色

    consul acl role create -name "otherRegister" -description "Only services
    with a prefix other than 'main' are allowed to register" -policy-name
    service-w -policy-name service-main-deny &> /dev/null


    #创建mainserver的token

    consul acl token list  |grep -w mainRegister || consul acl token create 
    -description "mainServer service register" -role-name "mainRegister"

    #创建其他服务注册的token

    consul acl token list  |grep -w otherRegister || consul acl token create
    -description "other service register" -role-name "otherRegister"
kind: ConfigMap
metadata:
  name: consul-initpoicy-configmap-cm
  labels:
    app.oscro.io/name: consul-initpoicy
  namespace: oscro-v2
apiVersion: v1
