apiVersion: v1
kind: Pod
metadata:
  name: pod-with-raw-block-volume
spec:
  imagePullSecrets:
  - name: registry-secret
  containers:
    - name: fc-container
      image: octahub.8lab.cn:5000/base/ubuntu:18.04
      command: ["/bin/sh", "-c"]
      args: ["tail -f /dev/null"]
      volumeMounts:
      - name: data
        mountPath: /data
   #  - name: restore
   #    mountPath: /restore
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: raw-block-pvc
   #- name: restore
   #  persistentVolumeClaim:
   #    claimName: rbd-pvc-restore
