apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: rbd-pvc-snapshot
spec:
  volumeSnapshotClassName: csi-rbd-snapshotclass
  source:
    persistentVolumeClaimName: raw-block-pvc
