kind: PersistentVolumeClaim
spec:
  resources:
    requests:
      storage: 200Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: csi-rbd-sc
metadata:
  name: consumer-app-persistentvolumeclaim-pvc
  labels:
    app.oscro.io/name: consumer-app
  namespace: oscro-v2
apiVersion: v1
