kind: Deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app.oscro.io/name: consumer-app
  template:
    spec:
      volumes:
        - name: consumer-app-cm
          configMap:
            name: consumer-app-cm
        - name: consumer-app-persistentvolumeclaim-pvc
          persistentVolumeClaim:
            claimName: consumer-app-persistentvolumeclaim-pvc
      containers:
        - name: consumerapp
          # image: octahub.8lab.cn:5000/oscro/consumerapp:v2310131644
          image: octahub.8lab.cn:5000/oscro/octa-consumer-appdeploy-2.2-t:2312131636
          resources:
            limits:
              cpu: 100m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 500Mi
          volumeMounts:
            - name: consumer-app-cm
              subPath: conf.json
              mountPath: /usr/local/server/src/config/conf.json
            - name: consumer-app-persistentvolumeclaim-pvc
              mountPath: /data/oscro-v2/logs
      imagePullSecrets:
        - name: registry-secret
    metadata:
      labels:
        app.oscro.io/name: consumer-app
metadata:
  name: consumer-app-deployment-deploy
  labels:
    app.oscro.io/name: consumer-app
  namespace: oscro-v2
apiVersion: apps/v1
