---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ceph-mgr-deploy
spec:
  selector:
    matchLabels:
      app: mgr
  replicas: 1
  template:
    metadata:
      labels:
        app: mgr
    spec:
      restartPolicy: Always
      imagePullSecrets:
      - name: registry-secret
      containers:
      - name: mgr
        image: octahub.8lab.cn:5000/99/ceph-mgr:v220418
        volumeMounts:
          - mountPath: /etc/ceph/ceph.conf
            subPath: ceph.conf
            name: ceph-config
#          - mountPath: /etc/ceph/ceph.mon.keyring
#            subPath: ceph.mon.keyrin
#            name: ceph-mon-keyring
#          - mountPath: /etc/ceph/ceph.client.admin.keyring
#            subPath: ceph.client.admin.keyring
#            name: client-admin-keyring
      volumes:
      - name: ceph-config
        configMap:
          name: ceph-configmap
#      - name: client-admin-keyring
#        secret:
#          secretName: client-admin-keyring
#      - name: ceph-mon-keyring
#        secret:
#          secretName: ceph-mon-keyring
      hostNetwork: true
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: ceph-mon
                operator: In
                values:
                - ceph-mon
