kind: PersistentVolumeClaim
spec:
  resources:
    requests:
      storage: 200Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: csi-rbd-sc
metadata:
  name: mainserver-persistentvolumeclaim-pvc
  labels:
    app.oscro.io/name: mainserver
  namespace: oscro-v2
apiVersion: v1
