kind: Deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app.oscro.io/name: mainserver
  template:
    spec:
      volumes:
        - name: mainserver-cm
          configMap:
            name: mainserver-cm
        - name: mainserver-persistentvolumeclaim-pvc
          persistentVolumeClaim:
            claimName: mainserver-persistentvolumeclaim-pvc
      containers:
        - name: mainserver
          # image: octahub.8lab.cn:5000/oscro/octa-mainserver-2.2-t:2309071957 #2309041747
          image: octahub.8lab.cn:5000/oscro/mainserver:v2309271646
          resources:
            limits:
              cpu: 100m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 500Mi
          volumeMounts:
            - name: mainserver-cm
              subPath: conf.json
              mountPath: /usr/local/server/src/config/conf.json
            - name: mainserver-persistentvolumeclaim-pvc
              mountPath: /data/oscro-v2/logs
      imagePullSecrets:
        - name: registry-secret
    metadata:
      labels:
        app.oscro.io/name: mainserver
metadata:
  name: mainserver-deployment-deploy
  labels:
    app.oscro.io/name: mainserver
  namespace: oscro-v2
apiVersion: apps/v1
