---
apiVersion: v1
data:
  key: QVFEb1A3VmVZYkRKRkJBQURsb1YvbFJaQ0pJendGb2xYSi9malE9PQ==
kind: Secret
metadata:
  name: ceph-secret-user
  namespace: default
type: kubernetes.io/rbd
---
apiVersion: v1
data:
  key: QVFCTHJMSmVoTlpETmhBQXlpVE9rZzRXTFVRWDAvRW8wSUV4TUE9PQ==
kind: Secret
metadata:
  name: ceph-secret-admin
  namespace: kube-system
type: kubernetes.io/rbd
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: rbd
provisioner: kubernetes.io/rbd
parameters:
  monitors: 192.168.1.129:6789
  adminId: admin
  adminSecretName: ceph-secret-admin
  adminSecretNamespace: kube-system
  pool: rbd_pool
  userId: rbd_pool
  userSecretName: ceph-secret-user
  fsType: xfs
  imageFormat: "2"
  imageFeatures: "layering"
