#apiVersion: v1
#kind: Service
#metadata:
#  name: mysql
#spec:
#  type: ClusterIP
#  clusterIP: 10.254.49.169
#  ports:
#  - name: mysql
#    port: 3306
#    protocol: TCP
#    targetPort: 3306
#  selector:
#    app.oscro.io/name: mysql

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  annotations:
    prometheus.io/http-probe: "true"
    prometheus.io/http-probe-port: "8080"
    prometheus.io/http-probe-path: "/healthCheck"
spec:
  ports:
  - port: 3306
    targetPort: 3306
    name: mysql
    protocol: TCP
  selector:
    app.oscro.io/name: mysql
  externalIPs:
    - 192.168.2.253

