apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
#  serviceName: mysql
  selector:
    matchLabels:
      app.oscro.io/name: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app.oscro.io/name: mysql
    spec:
      securityContext:
        sysctls:
        - name: net.core.somaxconn
          value: "2048"
      imagePullSecrets:
      - name: registry-secret
      containers:
      - name: mysql
        image: octahub.8lab.cn:5000/99/mysql:v0826
        #imagePullPolicy: Never
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: host-time  
          mountPath: /etc/localtime
          readOnly: true
        - name: mysql-tmp
          mountPath: /data/tmp
        - name: mysql-data
          mountPath: /data/mysql3306
        - name: mysql-conf
          mountPath: /opt/my3306.cnf
          subPath: my3306.cnf
        resources:
          requests:
            cpu: "1"
            memory: "6Gi"
          limits:
            cpu: "4"
            memory: "8Gi"
      - name: mysqld-exporter
        image: octahub.8lab.cn:5000/99/mysqld_exporter:v0617
        imagePullPolicy: Always
        ports:
        - containerPort: 9104
          name: exporter
        volumeMounts:
        - name: mysql-exporterconf
          mountPath: /usr/local/mysqld_exporter/.my3306.cnf
          subPath: .my3306.cnf
      volumes:
      - name: host-time
        hostPath:
          path: /etc/localtime
      - name: mysql-tmp
        emptyDir: {}
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-data-pvc
      - name: mysql-conf
        configMap:
          name: mysql-master
      - name: mysql-exporterconf
        configMap:
          name: mysql-exporter-cm
