---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: mysql-logs-pvc
#spec:
#  accessModes:
#    - ReadWriteOnce
#  storageClassName: rbd
#  resources:
#    requests:
#      storage: 25Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: csi-rbd-sc 
  resources:
    requests:
      storage: 150Gi
