global:
  scrape_interval:     30s    # 多久 收集 一次数据
  evaluation_interval: 30s    # 多久 评估 一次规则
  scrape_timeout:      10s    # 每次 收集数据的 超时时间


# 收集数据 配置 列表
scrape_configs:
  - job_name: 47.243.67.39 
    static_configs:
      - targets: ['eagle.tusima.l2:9010']
        labels:
          instance: "eagle.tusima.l2:9010"
          location: "hongkong"
      - targets: ['eagle.tusima.l2:9024']
        labels:
          instance: "eagle.tusima.l2:9024"
          location: "hongkong"

  - job_name: 8.210.124.146 
    static_configs:
      - targets: ['browserserver:9010']
        labels:
          instance: "browserserver:9010"
          location: "hongkong"
      - targets: ['browserserver:9024']
        labels:
          instance: "browserserver:9024"
          location: "hongkong"

            #   - job_name: 47.243.86.140
            #     static_configs:
            #       - targets: ['zk-relay:9024']
            #         labels:
            #           instance: "zk-relay:9024"
            #           location: "hongkong"
            #       - targets: ['zk-relay:9010']
            #         labels:
            #           instance: "zk-relay:9010"
            #           location: "hongkong"
            # 
            # - job_name: 47.243.202.216 
            #   static_configs:
            #     - targets: ['prover-server:9024']
            #       labels:
            #         instance: "prover-server:9024"
            #         location: "hongkong"
            #     - targets: ['prover-server:9010']
            #       labels:
            #         instance: "prover-server:9010"
            #         location: "hongkong"

  - job_name: 47.76.174.197
    static_configs:
      - targets: ['l2-197:9023']
        labels:
          instance: "l2-197:9023"
          location: "hongkong"
      - targets: ['l2-197:9024']
        labels:
          instance: "l2-197:9024"
          location: "hongkong"

  - job_name: 8.217.175.179 
    static_configs:
      - targets: ['l2-179:9010']
        labels:
          instance: "l2-179:9010"
          location: "hongkong"
      - targets: ['l2-179:9024']
        labels:
          instance: "l2-179:9024"
          location: "hongkong"
            
  - job_name: 47.242.127.155 
    static_configs:
      - targets: ['guanwang:9024']
        labels:
          instance: "guanwang:9024"
          location: "hongkong"
      - targets: ['guanwang:9010']
        labels:
          instance: "guanwang:9010"
          location: "hongkong"

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - 172.19.23.177:9025         #指定告警模块

rule_files:                      #告警规则文件, 可以使用通配符 
  - rules/*.yml
