apiVersion: v1
kind: ConfigMap
metadata:
  name: ceph-configmap
  namespace: default
data:
  ceph.conf: |
    [global]
    fsid = 5a68abff-e80f-4df4-8e0f-08d9bdced721
    mon_initial_members = pls-k8s-98
    mon_host = 192.168.1.98
    auth_cluster_required = cephx
    auth_service_required = cephx
    auth_client_required = cephx
    public_network = 192.168.1.0/24     #管理网络
    cluster_network = 192.168.1.0/24    #集群网络
    osd journal size = 1024
    osd pool default size = 3
    osd pool default min size = 2
    osd pool default pg num = 520
    osd pool default pgp num = 520
    mon allow pool delete = true
    osd max object name len = 2048
    osd max object namespace len = 256

    [mgr]
    mgr_host = pls-k8s-98
    mgr modules = dashboard             #开启mgr模板
