kind: Service
spec:
  type: ClusterIP
  ports:
    - name: mainport
      port: 10084
      protocol: TCP
      targetPort: 10084
  selector:
    app.oscro.io/name: demandserver
  externalIPs:
    - 192.168.1.96
metadata:
  name: demandserver-svc
  labels:
    app.oscro.io/name: demandserver
  namespace: oscro-v2
apiVersion: v1
