data:
  acl.json: |-
    {
      "acl": {
        "enabled": true,
        "default_policy": "deny",
        "enable_token_persistence": true,
        "tokens": {
          "initial_management": "fd40c378-e9ab-f5fd-7bfa-ed732824c0c8",
          "agent": "fd40c378-e9ab-f5fd-7bfa-ed732824c0c8"
        }
      }
    }
kind: ConfigMap
metadata:
  name: consul-client-configmap-cm
  labels:
    app.oscro.io/name: consul-client
  namespace: oscro-v2
apiVersion: v1
