apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: image-cache
  namespace: default
spec:
  params:
  - description: Cache image
    name: cacheImage
 #results:
 #- description: cache imagenames 
 #  name: cacheImages
 #  type: array
  steps:
  - args:
    - --cache-dir=/cache
    - --insecure-pull=true
    - --image=$(params.cacheImage)
    image: octahub.8lab.cn:5000/tekton/warmer:v2305
    command:
    - /kaniko/warmer
    name: image-cache
    volumeMounts:
    - mountPath: /cache
      name: kaniko-cache
    - mountPath: /etc/hosts
      name: hosts
  volumes:
  - hostPath:
      path: /data/kaniko-cache
    name: kaniko-cache
  - hostPath:
      path: /etc/hosts
    name: hosts
  workspaces:
  - description: Includes a docker `config.json`
    mountPath: /kaniko/.docker
    name: dockerconfig
    optional: true
