kind: ConfigMap
apiVersion: v1
metadata:
  name: oauth-cm
data:
  config.yaml: |-
    #Database related configuration
    db:
      type: mysql
      host: mysql-service.default:3306
      username: 8lab
      password: 8lab
      databaseName: oauth2
      maxIdleConns: 50
      maxOpenConns: 50
      connMaxLifetime: 60s
      connMaxIdleTime: 60s
      codeGCTimeInterval: 600s

    #https tls
    tls:
      certFile: /usr/local/oauth/certs/oauth.crt
      keyFile: /usr/local/oauth/certs/oauth.key

    jwe:
      rsaPrivateFile: /usr/local/oauth/rsa/oauth.priv
      rsaPublickFile: /usr/local/oauth/rsa/oauth.pub
      tokenTTL: 15m
    email:
      address: "smtp.ym.163.com"
      port: 25
      username: #default oscro@ethanim.network
      password:
