apiVersion: v1
kind: ConfigMap
metadata:
  name: oauth-frontend-cm
  namespace: default
data:
  oauth.conf: | 
    server {
      listen         8080;
      server_name    .*;
      charset UTF-8;
      underscores_in_headers  on;
      #access_log      /data/logs/myweb_access.log;
      error_log       /data/logs/nginx/error_fuzhou.log;
        ssl on;
        ssl_certificate /certs/oauth.crt;
        ssl_certificate_key /certs/oauth.key;
        ssl_session_timeout 5m;
        ssl_protocols TLSv1.1 TLSv1.2; #按照这个协议配置
        ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:HIGH:!aNULL:!MD5:!RC4:!DHE;#按照这个套件配置
        ssl_prefer_server_ciphers on;
    

      root        /usr/local/oauth/dist/;
            client_max_body_size 75M;
    
            location /api {
                proxy_pass https://127.0.0.1:9001;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            }

          location / {
            try_files $uri $uri/ /index.html;
            index /index.html;
          }
        }

