kind: Deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app.oscro.io/name: source-ms
  template:
    spec:
      volumes:
        - name: source-ms-cm
          configMap:
            name: source-ms-cm
        - name: source-ms-persistentvolumeclaim-pvc
          persistentVolumeClaim:
            claimName: source-ms-persistentvolumeclaim-pvc
      containers:
        - name: source-ms
          # image: octahub.8lab.cn:5000/oscro/sourcemanageserver:v2310161730
          image: octahub.8lab.cn:5000/oscro/octa-sourceserver-v2.2-1:2312011719 
          resources:
            limits:
              cpu: 100m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 500Mi
          volumeMounts:
            - name: source-ms-cm
              subPath: conf.json
              mountPath: /usr/local/server/src/config/conf.json
            - name: source-ms-persistentvolumeclaim-pvc
              mountPath: /data/oscro-v2/logs
      imagePullSecrets:
        - name: registry-secret
    metadata:
      labels:
        app.oscro.io/name: source-ms
metadata:
  name: source-ms-deployment-deploy
  labels:
    app.oscro.io/name: source-ms
  namespace: oscro-v2
apiVersion: apps/v1
