apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.k8s.io/name: application-controller
  name: application-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app.k8s.io/name: application-controller
  template:
    metadata:
      labels:
        app.k8s.io/name: application-controller
    spec:
      imagePullSecrets:
      - name: registry-secret
      containers:
      - args:
       #- -leader-elect
        - -not-add-owner="PersistentVolume,PersistentVolumeClaim,PipelineRun"
        - -refresh-time=60s
        - -zap-time-encoding=rfc3339
        image: octahub.8lab.cn:5000/99/application-controller:v20230321
        imagePullPolicy: Always
        name: application-controller
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 20Mi
      terminationGracePeriodSeconds: 10
      serviceAccountName: application-controller-sa
