apiVersion: v1
kind: Service
metadata:
  name: harborserver-svc
  namespace: default 
  labels:
    app: harborserver 
spec:
  selector:
    app: harborserver
  ports:
  - name: hbproxyweb
    port: 9096
    targetPort: 9096
  externalIPs:
    - 192.168.1.97

