apiVersion: v1
kind: ConfigMap
metadata:
  name: harborserver-cm
  namespace: default
  labels:
    app: harborserver
data:
  conf.json: |
    {
      "app": {
        "app_name": "harborServer",
        "app_addr": "0.0.0.0",
        "app_port": "9096"
      },
      "log": {
        "log_path": "/var/log/server"
      },
      "consul": {
        "server_ip": "192.168.24.177",
        "server_port": "8500"
      },
      "db": {
        "db_name": "mainportal-0820",
        "db_host": "192.168.1.99",
        "db_port": "3306",
        "db_user": "8lab",
        "db_passwd": "8lab"
      },
      "harbor": {
        "default_pwd": "Octa8lab!!"
      }
    }
