apiVersion: apps/v1
kind: Deployment
metadata:
  name: harborserver-deploy
  namespace: default
  labels:
    app: harborserver
spec:
  selector:
    matchLabels:
      app: harborserver
  replicas: 1
  template:
    metadata:
      labels:
        app: harborserver
    spec:
      imagePullSecrets:
      - name: registry-secret
      containers:
      - name: harborserver
        image: octahub.8lab.cn:5000/99/octa_harbor_server:v2302281111 # v2302241621
        imagePullPolicy: IfNotPresent
        ports:
        - name: harborserver
          containerPort: 9096
          protocol: TCP
        volumeMounts:
        - name: server-conf
          mountPath: /usr/local/octa_harborserver/src/config/conf.json
          subPath: conf.json
      volumes:
      - name: server-conf
        configMap:
          name: harborserver-cm 
