apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik-ingress-controller

---
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: traefik-ds
  labels:
    app: traefik
spec:
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      priorityClassName: system-node-critical
      serviceAccountName: traefik-ingress-controller
      imagePullSecrets:
      - name: registry-secret
      containers:
      - name: traefik
        image: octahub.8lab.cn:5000/99/traefik:v0918
        imagePullPolicy: Always
        args:
          - --log=true
          - --log.level=INFO
          - --log.format=json
          - --accesslog=true
          - --accesslog.format=json
          - --api
          - --api.insecure
          - --ping=true
          - --metrics=true
          - --metrics.prometheus.addEntryPointsLabels=true
          - --metrics.prometheus.addServicesLabels=true
          - --metrics.prometheus=true
          - --entrypoints.web.address=:80
          - --entrypoints.websecure.address=:443
          - --providers.kubernetescrd
          - --global.sendAnonymousUsage
        ports:
          - name: web
            containerPort: 80
            hostPort: 80
          - name: websecure
            containerPort: 443
            hostPort: 443
          - name: admin
            containerPort: 8080
            hostPort: 8080
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: traefik
                operator: In
                values:
                - traefik
