kind: Application
spec:
  selector:
    matchLabels:
      app.oscro.io/name: mainserver
  addOwnerRef: true
  componentKinds:
    - kind: PipelineRun
      group: tekton.dev
    - kind: ConfigMap
      group: v1
    - kind: Deployment
      group: apps
    - kind: Service
      group: v1
    - kind: PersistentVolumeClaim
      group: v1
metadata:
  name: mainserver
  namespace: oscro-v2
  finalizers:
    - foregroundDeletion
apiVersion: app.oscro.io/v1beta1
