kind: Service
spec:
  type: ClusterIP
  ports:
    - name: appport
      port: 10087
      protocol: TCP
      targetPort: 10087
  selector:
    app.oscro.io/name: appserver
  externalIPs:
    - 192.168.1.96
metadata:
  name: appserver-svc
  labels:
    app.oscro.io/name: appserver
  namespace: oscro-v2
apiVersion: v1
