apiVersion: v1
kind: ServiceAccount
metadata:
  name: ops-wuqiong
  namespace: l4-test-a123 

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ops-wuqiong-rb
  namespace: l4-test-a123 
roleRef:
  apiGroup: rbac.authorization.k8s.io 
  kind: Role
  name: rbd-test 
subjects:
- kind: ServiceAccount
  name: ops-wuqiong
  namespace: l4-test-a123 

