apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rbd-test
  namespace: l4-test-a123 
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
