apiVersion: v1
kind: Service
metadata:
  name:  trias-one-svc 
  namespace: l4-test-a123 
  labels:
    app.oscro.io/name: "trias-one" 
spec:
  ports:
  - port: 8400
    targetPort: 8400
    name: "nginx"
    protocol: TCP
  selector:
    app.oscro.io/name: "trias-one"
  externalIPs:
    - 103.210.160.246
