apiVersion: v1
kind: ConfigMap
metadata:
  name: consul-acl-cm
data:
  acl.json: |-
    {
      "acl": {
        "enabled": true,
        "default_policy": "deny",
        "enable_token_persistence": true,
        "tokens": {
          "initial_management": "fd40c378-e9ab-f5fd-7bfa-ed732824c0c8",
          "agent": "fd40c378-e9ab-f5fd-7bfa-ed732824c0c8"
        }
      }
    }
