apiVersion: apps/v1
kind: StatefulSet
metadata:
 name: consul-client-sts
 labels:
  name: consul-client
spec:
  selector:
    matchLabels:
      name: consul-client
  replicas: 3
  serviceName: consul-client-svc
  template:
    metadata:
      labels:
        name: consul-client
    spec:
      imagePullSecrets:
      - name: registry-secret
      containers:
        - name: consul
          image: octahub.8lab.cn:5000/99/consul:v1.15.2
          imagePullPolicy: Always
          args:
            - "agent"
            - "-config-dir=/usr/local/consul/config"
            - "-ui"
            - "-data-dir=/data/consul"
            - "-bind=0.0.0.0"
            - "-client=0.0.0.0"
            - "-advertise=$(POD_IP)"
            - "-retry-join=consul-server-sts-0.consul-server-svc.$(NAMESPACE).svc.cluster.local"
            - "-retry-join=consul-server-sts-1.consul-server-svc.$(NAMESPACE).svc.cluster.local"
            - "-retry-join=consul-server-sts-2.consul-server-svc.$(NAMESPACE).svc.cluster.local"
            - "-domain=cluster.local"
            - "-disable-host-node-id"
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          lifecycle:
            postStart:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - export CONSUL_HTTP_TOKEN=`grep -r initial /usr/local/consul/config/|awk -F'"' '{print $4}'` && consul reload
            preStop:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - export CONSUL_HTTP_TOKEN=`grep -r initial /usr/local/consul/config/|awk -F'"' '{print $4}'` && consul leave
                 #- consul leave
          volumeMounts:
           - name: consul-data
             mountPath: /consul/data
           - name: acl-cm
             mountPath: /usr/local/consul/config
          ports:
            - containerPort: 8500
          #   hostPort: 8500
              name: http
            - containerPort: 8400
              name: rpc
            - containerPort: 8443
              name: https
            - containerPort: 8301
              name: serf-lan
            - containerPort: 8302
              name: serf-wan
            - containerPort: 8600
              name: consul
            - containerPort: 8300
              name: server
      volumes:
     #- name: consul-data
     #  hostPath:
     #    path: /data/consul-client
      - name: acl-cm
        configMap:
          name: consul-acl-cm
  volumeClaimTemplates:
  - metadata:
      name: consul-data
    spec:
      storageClassName: "csi-rbd-sc"
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
