apiVersion: batch/v1
kind: Job
metadata:
  name: consul-initpolicy-job
spec:
  ttlSecondsAfterFinished: 100
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      imagePullSecrets:
      - name: registry-secret
      initContainers:
      - name: wait-for-consul
        image: octahub.8lab.cn:5000/99/busybox:1.28
        command: 
        - sh
        - -c
        args:
        - until wget -q -O - http://consul-client-svc:8500/v1/status/leader 2>/dev/null | grep -E '".+"'; do echo waiting for consul; sleep 2; done;
      containers:
      - name: init-policy
        image: octahub.8lab.cn:5000/99/consul:v1.15.2
        command:
        - sh
        - -c
        args:
        - /tmp/initpolicy.sh
        env:
        - name: "CONSUL_HTTP_ADDR"
          value: "http://consul-client-svc:8500" 
        volumeMounts:
          - name: acl-cm
            mountPath: /data/config
          - name: initsh
            mountPath: /tmp/
      volumes:
      - name: acl-cm
        configMap:
          name: consul-acl-cm
      - name: initsh
        configMap:
          defaultMode: 0777
          name: consul-initsh-cm
