apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: consul-server-sts
  labels:
    name: consul-server
spec:
  serviceName: consul-server-svc
  selector:
    matchLabels:
      name: consul-server
  replicas: 3
  template:
    metadata:
      labels:
        name: consul-server
    spec:
      terminationGracePeriodSeconds: 10
      imagePullSecrets:
      - name: registry-secret
      containers:
        - name: consul
          image: octahub.8lab.cn:5000/99/consul:v1.15.2
         #imagePullPolicy: IfNotPresent
          imagePullPolicy: Always
          args:
            - "agent"
            - "-server"
            - "-config-dir=/usr/local/consul/config"
            - "-bootstrap-expect=3"
            - "-data-dir=/data/consul"
            - "-bind=0.0.0.0"
            - "-client=0.0.0.0"
            - "-advertise=$(POD_IP)"
            - "-retry-join=consul-server-sts-0.consul-server-svc.$(NAMESPACE).svc.cluster.local"
            - "-retry-join=consul-server-sts-1.consul-server-svc.$(NAMESPACE).svc.cluster.local"
            - "-retry-join=consul-server-sts-2.consul-server-svc.$(NAMESPACE).svc.cluster.local"
            - "-domain=cluster.local"
            - "-disable-host-node-id"
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - containerPort: 8500
              name: http
            - containerPort: 8400
              name: rpc
            - containerPort: 8443
              name: https-port
            - containerPort: 8301
              name: serf-lan
            - containerPort: 8302
              name: serf-wan
            - containerPort: 8600
              name: consul-dns
            - containerPort: 8300
              name: server
          volumeMounts:
          - name: consul-data
            mountPath: /data/consul
          - name: acl-cm
            mountPath: /usr/local/consul/config
      volumes:
        - name: acl-cm
          configMap:
            name: consul-acl-cm
  volumeClaimTemplates:
  - metadata:
      name: consul-data
    spec:
      storageClassName: "csi-rbd-sc"
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi
