apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: k8s-webhook-validating
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUR0RENDQXB5Z0F3SUJBZ0lVSHU2aUVvWVkvYjhVa3ZiTDlqZWNxZHlpY2ZFd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1lERVZNQk1HQTFVRUJ4TU1kR2hsSUdsdWRHVnlibVYwTVJZd0ZBWURWUVFLRXcxaGRYUnZaMlZ1WlhKaApkR1ZrTVJVd0V3WURWUVFMRXd3NGJHRmlJR05zZFhOMFpYSXhHREFXQmdOVkJBTVREemhzWVdJZ1lYVjBiMmRsCmJpQkRRVEFlRncweU1qQTJNekF4TVRJNU1EQmFGdzB5TnpBMk1qa3hNVEk1TURCYU1HQXhGVEFUQmdOVkJBY1QKREhSb1pTQnBiblJsY201bGRERVdNQlFHQTFVRUNoTU5ZWFYwYjJkbGJtVnlZWFJsWkRFVk1CTUdBMVVFQ3hNTQpPR3hoWWlCamJIVnpkR1Z5TVJnd0ZnWURWUVFERXc4NGJHRmlJR0YxZEc5blpXNGdRMEV3Z2dFaU1BMEdDU3FHClNJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUUM4a0hGQytaWUpjSkhSUjFJOFVhQmQxTXBDWXp6Rk1jZ2EKaSs0M2lOSGNpSEJENnhMbjZWcko1VzFMZUw1RGh1dldNZkFUSEtMNDJWUklZYkVxQkF6UVBRenN4SlBBQnlLaQp4VlRaSjhxTzR6Ump3QmZKYnh2U0pveUVwRC9aTE93clhkWnVMTnBoTTVYRXRaZWlLbWhNKzU4YzNaaUVpMzRrCmZNWFd1UFhaMFE1RFBjZml5LzVyNnVudnJsVzRkQklPUGtGSXVOTnlVYVVwbG5qU3VFOEJFckFjU0VzbFNMK08KRElNSXE5RHd6dEdzdTNyakFnSTcvdTBQN1Vqb2ZFODhBbk0zaTNjdGZJMUh0WFI2dEYzN25lU0RFMm00S3ZnUwpxRmgzVlZwYTRvdHZuQ210VkdmNkVOZ202YkpYWFVhejVFeGFiRnQ0dk9HcWp1U0traDRkQWdNQkFBR2paakJrCk1BNEdBMVVkRHdFQi93UUVBd0lCQmpBU0JnTlZIUk1CQWY4RUNEQUdBUUgvQWdFQ01CMEdBMVVkRGdRV0JCUTcKNUZETjRNTW1EOTVPWTY3ci80R00ySHJ0ZkRBZkJnTlZIU01FR0RBV2dCUTc1RkRONE1NbUQ5NU9ZNjdyLzRHTQoySHJ0ZkRBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQWpwajFoaWJ2RDd0cUFtNmdYb3VibWV3b2JsOCs1ZlhqCmM2c2RMd2hCWjZPNDR2TVBLSTZMTW1oNjdrNldrTE14TEw5ay82eWl5Vmh4SVBxU0RxOE5Ic1NET0F2MUI5cXMKSmZkUmQ3NjZoVVp4TnczNnpLMGQvd0VoT0hmV3RQUktPUVdVMUw2SGgyNEsybTZTNUFKTDdhQTVLZHprUEo4bQppOTkrY3BSdFM2czJjaVVxVTJFU3hHeXFBelY1UDhVdnZ3UExrYUxMNTFBYjUwZU45NnRTZnQvSmN3R0lQVjQ4CkVETUZibExjU2FvbTNpVVBvVDEyT21HTXBjcUp6RGRsd1pUVWdOVFVhb1VEb0dFeTJjR1Q0cm1mTGc1bTBxdncKWDNRbW5IcjZYL3FDSmwzb20yVEZmb0E2cHlXSGwrNWg0MVFJc0VUZFVTRWh6VU5vREFSK0xBPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo= 
   #url or service
   #url: https://192.168.1.98:9003/services
    service:
      name: k8s-webhook-svc 
      namespace: default
      path: /validate-service-conflict
     #path: /services
      port: 8080
  failurePolicy: Ignore
  matchPolicy: Equivalent
  name: service.address.conflict
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - services
    scope: '*'
  sideEffects: None
  timeoutSeconds: 5
