apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-webhook-sa
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-webhook-cr
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - services
  verbs:
  - get
  - list
  - watch

---    
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-webhook-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8s-webhook-cr
subjects:
- kind: ServiceAccount
  name: k8s-webhook-sa
  namespace: default
