---
apiVersion: v1
kind: Service
metadata:
  name: ck-svc
  namespace: appdata
spec:
  ports:
  - port: 9181
    targetPort: 9181
    name: ck-keeper
  - port: 9444
    targetPort: 9444
    name: ck-keeper-raft
  - port: 9000
    targetPort: 9000
    name: tcp
  - port: 8123
    targetPort: 8123
    name: http
  - port: 9009
    targetPort: 9009
    name: ck-server-peer
  selector:
    app: ck
