kind: Service
spec:
  type: ClusterIP
  ports:
    - name: port
      port: 10086
      protocol: TCP
      targetPort: 10086
  selector:
    app.oscro.io/name: auditserver
  externalIPs:
    - 192.168.1.96
metadata:
  name: auditserver-svc
  labels:
    app.oscro.io/name: auditserver
  namespace: oscro-v2
apiVersion: v1
