kind: Deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app.oscro.io/name: nsqlookupd
  template:
    spec:
      containers:
        - args:
            - nsqlookupd
          name: nsq
          image: octahub.8lab.cn:5000/oscro/nsq:v1.2.1
          resources:
            limits:
              cpu: 100m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 500Mi
          imagePullPolicy: Always
      restartPolicy: Always
      imagePullSecrets:
        - name: registry-secret
    metadata:
      labels:
        app.oscro.io/name: nsqlookupd
metadata:
  name: nsqlookupd-deployment-deploy
  labels:
    app.oscro.io/name: nsqlookupd
  namespace: oscro-v2
apiVersion: apps/v1
