kind: Service
spec:
  type: ClusterIP
  ports:
    - name: authport
      port: 10081
      protocol: TCP
      targetPort: 10081
  selector:
    app.oscro.io/name: authserver
  externalIPs:
    - 192.168.1.96
metadata:
  name: authserver-svc
  labels:
    app.oscro.io/name: authserver
  namespace: oscro-v2
apiVersion: v1
