kind: ConfigMap
apiVersion: v1
metadata:
  name: kubeopt-cm
data:
  oscro.yaml: |-
    authentication:
      clientCert:
        clientCa: /run/secrets/kubernetes.io/serviceaccount/ca.crt
    logging:
      endpoint: ck-svc.logging.svc.cluster.local:9000
      password: octa8lab
      username: octa8lab
    network:
      endpoint: weave-scope-app:4040
    mysql:
      endpoint: mysql-service:3306
      password: 8lab
      username: 8lab
      database: pipelineruns
      maxIdleConns: 50
      maxOpenConns: 50
      connMaxLifetime: 60s
      connMaxIdleTime: 30s
    tekton:
      keep: 1
      gcTimeInterval: 1m
    ceph:
      endpoint: #http://192.168.1.98:7480 ceph rgw
      accessKey: AAZWV7WL14R36UY2DVP4
      secretKey: ffykiDX58kXF8ZweHSN3CXq7zJSWmahjOYw3Yxys
    octack:
      accessAddress: "ck-svc.appdata"
      accessPort: "9000/TCP,8123/HTTP"
      controlNS: "default" #octack namespace
      controlEndpoint: "" #octack external地址.如果为空通过controlNS自动获取octack-svc IP:PORT
