data:
  config.ini: |
    [service]
    Mode = release
    Port = 10089
    Address = 192.168.1.96
    Name = accountServer

    [mysql]
    Db = mysql
    DbAddress = 192.168.1.99
    DbPort = 3306
    DbUser = 8lab
    DbPassWord = 8lab
    DbName = oscro
    Charset = utf8mb4

    [consul]
    Address = 192.168.1.97
    Port = 8500
    Token = b408de14-17e3-216a-cd74-124a6a3914de 
    NodeSide = 3 

    [log]
    Path = /data/oscro-v2/logs 
    SaveDay = 7

    [key]
    AccountKey = 4dxdL1bOclQ63AUxGkB2ei1n2FwUTbQ3gEv

    [auth]
    AuthServerName = authServer

    [oauth2]
    ServerHost = https://192.168.1.178:3000

kind: ConfigMap
metadata:
  name: accountserver-cm
  labels:
    app.oscro.io/name: accountserver
  namespace: oscro-v2
apiVersion: v1
