kind: Service
spec:
  type: ClusterIP
  ports:
    - name: accountport
      port: 10089
      protocol: TCP
      targetPort: 10089
  selector:
    app.oscro.io/name: accountserver
  externalIPs:
    - 192.168.1.96
metadata:
  name: accountserver-svc
  labels:
    app.oscro.io/name: accountserver
  namespace: oscro-v2
apiVersion: v1
