apiVersion: v1
kind: ServiceAccount
metadata:
  name: user-controller-sa
  namespace: default
  labels:
    app.k8s.io/name: user-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: user-controller-cr
  labels:
    app.k8s.io/name: user-controller
rules:
- apiGroups:
  - user.oscro.io
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - rolebindings
  - clusterroles
  verbs:
  - "*" 
- apiGroups:
  - coordination.k8s.io
  resources:
  - "*"
  verbs:
  - "*" 
- apiGroups:
  - certificates.k8s.io
  resources:
  - "*"
  verbs:
  - "*" 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: user-controller-crb
  labels:
    app.k8s.io/name: user-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: user-controller-cr
subjects:
- kind: ServiceAccount
  name: user-controller-sa
  namespace: default
