kind: Deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app.oscro.io/name: auditserver
  template:
    spec:
      volumes:
        - name: auditserver-configmap-cm
          configMap:
            name: auditserver-configmap-cm
        - name: auditserver-persistentvolumeclaim-pvc
          persistentVolumeClaim:
            claimName: auditserver-persistentvolumeclaim-pvc
      containers:
        - name: auditserver
          image: octahub.8lab.cn:5000/oscro/octa-auditserver-master-p:2306141625
          resources:
            limits:
              cpu: 100m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 500Mi
          volumeMounts:
            - name: auditserver-configmap-cm
              subPath: conf.json
              mountPath: /usr/local/server/src/config/conf.json
            - name: auditserver-persistentvolumeclaim-pvc
              mountPath: /data/oscro-v2/logs
      imagePullSecrets:
        - name: registry-secret
    metadata:
      labels:
        app.oscro.io/name: auditserver
metadata:
  name: auditserver-deployment-deploy
  labels:
    app.oscro.io/name: auditserver
  namespace: oscro-v2
apiVersion: apps/v1
