apiVersion: apps/v1
kind: Deployment
metadata:
  name: nsqlookupd-deploy
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nsqlookupd
  template:
    metadata:
      labels:
        app: nsqlookupd
    spec:
      imagePullSecrets:
      - name: registry-secret
      containers:
      - name: nsq
        image: octahub.8lab.cn:5000/99/nsq:v1.2.1
        imagePullPolicy: Always
        args:
        - nsqlookupd
        resources:
          limits:
            cpu: 100m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 500Mi
      restartPolicy: Always
