kind: Service
apiVersion: v1
metadata:
  name: nsqadmin-svc
  namespace: default
spec:
  ports:
  - port: 4171
    targetPort: 4171
    name: http
  selector:
    app: nsqadmin
  externalIPs:
    - 192.168.1.98
