apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nsqd-data-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: csi-rbd-sc 
  resources:
    requests:
      storage: 10Gi
