---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ceph-mgr-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ceph-mgr
  template:
    metadata:
      labels:
        app: ceph-mgr
    spec:
      restartPolicy: Always
      imagePullSecrets:
      - name: registry-secret
      containers:
      - name: mgr
        image: octahub.8lab.cn:5000/99/ceph-mgr:17.2.5
        imagePullPolicy: Always
        args:
        - --public-addr=$(POD_IP)
        - --public-bind-addr=$(POD_IP)
        - --conf=/etc/ceph/ceph.conf
        - -d 
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
          - mountPath: /etc/ceph/ceph.conf
            subPath: ceph.conf
            name: ceph-cm
          - mountPath: /etc/ceph/ceph.client.admin.keyring
            subPath: ceph.client.admin.keyring
            name: ceph-keyring
      volumes:
      - name: ceph-cm
        configMap:
          name: ceph-cm
      - name: ceph-keyring
        secret:
          secretName: ceph-keyring
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - ceph-mgr
              topologyKey: kubernetes.io/hostname
