apiVersion: batch/v1
kind: Job
metadata:
  name: ceph-initpool-job
spec:
  ttlSecondsAfterFinished: 100
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      imagePullSecrets:
      - name: registry-secret
      initContainers:
      - name: wait-for-mon
        image: octahub.8lab.cn:5000/99/ceph-mon:17.2.5
        command: 
        - sh
        - -c
        args:
        - until ceph mon stat; do echo waiting for monitor; sleep 2; done;
        volumeMounts:
          - mountPath: /etc/ceph/ceph.conf
            subPath: ceph.conf
            name: ceph-cm
          - mountPath: /etc/ceph/ceph.client.admin.keyring
            subPath: ceph.client.admin.keyring
            name: ceph-keyring
      containers:
      - name: init-pool
        image: octahub.8lab.cn:5000/99/ceph-mon:17.2.5
        command:
        - sh
        - -c
        args:
        - ceph osd pool create kubernetes && rbd pool init kubernetes
        volumeMounts:
          - mountPath: /etc/ceph/ceph.conf
            subPath: ceph.conf
            name: ceph-cm
          - mountPath: /etc/ceph/ceph.client.admin.keyring
            subPath: ceph.client.admin.keyring
            name: ceph-keyring
      volumes:
      - name: ceph-cm
        configMap:
          name: ceph-cm
      - name: ceph-keyring
        secret:
          secretName: ceph-keyring
