---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ceph-mon-ds
spec:
  selector:
    matchLabels:
      app: ceph-mon
  template:
    metadata:
      labels:
        app: ceph-mon
    spec:
      priorityClassName: system-node-critical
      restartPolicy: Always
      imagePullSecrets:
      - name: registry-secret
      initContainers:
      - name: chmod
        image: octahub.8lab.cn:5000/99/busybox:1.28
        imagePullPolicy: IfNotPresent
        command: ["sh", "-c", "chown -R 1000:1000 /data/ceph/mon"]
        volumeMounts:
          - name: mon-data
            mountPath: /data/ceph/mon
      containers:
      - name: mon
        image: octahub.8lab.cn:5000/99/ceph-mon:17.2.5
        imagePullPolicy: Always
        args:
        - --public-addr=$(POD_IP)
        - --public-bind-addr=$(POD_IP)
        - -d 
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        volumeMounts:
          - mountPath: /etc/ceph/ceph.conf
            subPath: ceph.conf
            name: ceph-cm
          - mountPath: /etc/ceph/ceph.mon.keyring
            subPath: ceph.mon.keyring
            name: ceph-keyring
          - mountPath: /etc/ceph/ceph.client.admin.keyring
            subPath: ceph.client.admin.keyring
            name: ceph-keyring
          - name: mon-data
            mountPath: /var/lib/ceph/mon
      volumes:
      - name: ceph-cm
        configMap:
          name: ceph-cm
      - name: mon-data
        hostPath:
          path: /data/ceph/mon/
      - name: ceph-keyring
        secret:
          secretName: ceph-keyring
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: ceph-mon-17
                operator: In
                values:
                - enabled
