kind: ConfigMap
apiVersion: v1
metadata:
  name: ceph-cm
data:
  ceph.conf: |
    [global]
      fsid = 5a68abff-e80f-4df4-8e0f-08d9bdced721
      mon_host = 192.168.1.98,192.168.1.97,192.168.1.96
      auth_cluster_required = cephx
      auth_service_required = cephx
      auth_client_required = cephx
      osd_pool_default_size = 3
      osd_pool_default_min_size = 2
      osd_pool_default_pg_num = 128
      osd_pool_default_pgp_num = 128
      mon_allow_pool_delete = true
      mon_max_pg_per_osd = 1000
      osd_pool_default_pg_autoscale_mode = off
      mon_cluster_log_to_file = false
      mon_cluster_log_to_stderr = true
