apiVersion: v1
kind: Secret
metadata:
  name: registry-secret
data:
  .dockerconfigjson: eyJhdXRocyI6eyJvY3RhaHViLjhsYWIuY246NTAwMCI6eyJ1c2VybmFtZSI6ImFkbWluIiwicGFzc3dvcmQiOiI3elVkWnN6Z2x0IiwiYXV0aCI6IllXUnRhVzQ2TjNwVlpGcHplbWRzZEE9PSJ9fX0= 
type: kubernetes.io/dockerconfigjson

