apiVersion: v1
kind: Namespace
metadata:
  name: tekton-pipelines-resolvers
  labels:
    app.kubernetes.io/component: resolvers
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-pipelines
    pod-security.kubernetes.io/enforce: restricted
---
apiVersion: v1
kind: Secret
metadata:
  name: registry-secret
  namespace: tekton-pipelines-resolvers
data:
  .dockerconfigjson: eyJhdXRocyI6eyJvY3RhaHViLjhsYWIuY246NTAwMCI6eyJ1c2VybmFtZSI6ImFkbWluIiwicGFzc3dvcmQiOiI3elVkWnN6Z2x0IiwiYXV0aCI6IllXUnRhVzQ2TjNwVlpGcHplbWRzZEE9PSJ9fX0= 
type: kubernetes.io/dockerconfigjson
