kind: Service
apiVersion: v1
metadata:
  name: nsqlookupd-svc
  namespace: default
spec:
  ports:
  - port: 4161
    targetPort: 4161
    name: http
  - port: 4160
    targetPort: 4160
    name: tcp
  selector:
    app: nsqlookupd
# externalIPs:
#   - 192.168.1.99
