apiVersion: apps/v1
kind: Deployment
metadata:
  name: nsqd-deployment-deploy #nsqd-deploy
  namespace: oscro-v2 
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nsqd
  template:
    metadata:
      labels:
        app: nsqd
    spec:
      imagePullSecrets:
      - name: registry-secret
      containers:
      - name: nsq
        image: octahub.8lab.cn:5000/99/nsq:v1.2.1
        imagePullPolicy: Always
        args:
        - nsqd  
        - --broadcast-address=$(POD_IP)
        - --lookupd-tcp-address=nsqlookupd-svc:4160
        - --data-path=/data/
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        volumeMounts:
        - name: nsqd-data
          mountPath: /data
        resources:
          limits:
            cpu: 100m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 500Mi
      restartPolicy: Always
      volumes:
      - name: nsqd-data
        persistentVolumeClaim:
          claimName: nsqd-data-pvc
