kind: Service
apiVersion: v1
metadata:
  name: nsqd-svc
  namespace: default
spec:
  ports:
  - port: 4151 
    targetPort: 4151
    name: http
  - port: 4150
    targetPort: 4150
    name: tcp
  selector:
    app: nsqd
# externalIPs:
#   - 192.168.1.99
