apiVersion: apps/v1
kind: Deployment
metadata:
  name: octack-deploy
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: octack
  template:
    metadata:
      labels:
        app: octack
    spec:
      imagePullSecrets:
      - name: registry-secret
      containers:
      - name: octack
       #image: octahub.8lab.cn:5000/99/octack:v231107
        image: octahub.8lab.cn:5000/99/octack:v231123
        imagePullPolicy: Always
        volumeMounts:
        - name: jwt
          subPath: validating.pub
          mountPath: /usr/local/octack/rsa/validating.pub
        - mountPath: "/usr/local/octack/config/config.yaml"
          subPath: config.yaml
          name: octack-cm
        args:
        - -c /usr/local/octack/config/config.yaml
        ports:
        - containerPort: 9000
          protocol: TCP
        resources:
          limits:
            cpu: 512m
            memory: 256Mi
          requests:
            cpu: 512m
            memory: 256Mi
      restartPolicy: Always
      volumes:
      - name: jwt
        secret: 
          secretName: octack-jwt-secret
      - name: octack-cm 
        configMap:
          name: octack-cm
