data:
  config.ini: |
    [service]
    Mode = release 
    Port = 10082
    Address = 192.168.1.96
    Name = devSceneServer

    [mysql]
    Db = mysql
    DbAddress = 192.168.1.99
    DbPort = 3306
    DbUser = 8lab
    DbPassWord = 8lab
    DbName = oscro
    Charset = utf8mb4

    [consul]
    Address = 192.168.1.97
    Port = 8500
    Token = b408de14-17e3-216a-cd74-124a6a3914de 
    NodeSide = 3 

    [log]
    Path = /data/oscro-v2/logs 
    SaveDay = 7

    [auth]
    AuthServerName = authServer
    AuthServerHost = http://192.168.1.96:10081

    [nsq]
    NsqD = nsqd-service-svc.oscro-v2:4150
    NsqLookupD = nsqlookupd-service-svc.oscro-v2:4161
    DevSceneCreate = D1E8FB37-BB2B-21DF-9AFF-74D24FF75EDD
    DevSceneDelete = 509AA3A7-2D16-D59E-DE1F-45003646DCB7
    DevScenePatch = 8F06378E-15F1-7F67-20DE-D7B048C06EEC
    DevSceneSyncStatus = 8F06378E-15F1-7F67-20DE-7SYNC0STATUS

kind: ConfigMap
metadata:
  name: devserver-cm
  labels:
    app.oscro.io/name: devserver
  namespace: oscro-v2
apiVersion: v1
