kind: Service
spec:
  type: ClusterIP
  ports:
    - name: devport
      port: 10082
      protocol: TCP
      targetPort: 10082
  selector:
    app.oscro.io/name: devserver
  externalIPs:
    - 192.168.1.96
metadata:
  name: devserver-svc
  labels:
    app.oscro.io/name: devserver
  namespace: oscro-v2
apiVersion: v1
