kind: Deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app.oscro.io/name: consumer-sms
  template:
    spec:
      volumes:
        - name: consumer-sms-cm
          configMap:
            name: consumer-sms-cm
        - name: consumer-sms-persistentvolumeclaim-pvc
          persistentVolumeClaim:
            claimName: consumer-sms-persistentvolumeclaim-pvc
      containers:
        - name: consumersms
          # image: octahub.8lab.cn:5000/oscro/consumersourcemanager:v2310161730
          image: octahub.8lab.cn:5000/oscro/octa-consumer-sms-2.2-t:2312131636 
          resources:
            limits:
              cpu: 100m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 500Mi
          volumeMounts:
            - name: consumer-sms-cm
              subPath: conf.json
              mountPath: /usr/local/server/src/config/conf.json
            - name: consumer-sms-persistentvolumeclaim-pvc
              mountPath: /data/oscro-v2/logs
      imagePullSecrets:
        - name: registry-secret
    metadata:
      labels:
        app.oscro.io/name: consumer-sms
metadata:
  name: consumer-sms-deployment-deploy
  labels:
    app.oscro.io/name: consumer-sms
  namespace: oscro-v2
apiVersion: apps/v1
