apiVersion: v1
kind: ConfigMap
metadata:
  name: plansvr-cm
  namespace: default
  labels:
    app: plansvr
data:
  config.json: |
    {
      "DB": {
        "dbHost": "mysql-service.default",
        "dbPort": 3306,
        "dbName": "mainportal-0820",
        "dbUser": "8lab",
        "dbPasswd": "8lab"
      },
      "Jwe": {
        "expTime": 9000,
        "priKey": "lib/auth/oauthRsa"
      },
      "logPath": "/var/log/PlanServer/"
    }

