apiVersion: v1
kind: Service
metadata:
  name: plansvr-svc
  namespace: default 
  labels:
    app: plansvr 
spec:
  selector:
    app: plansvr
  ports:
  - name: web
    port: 8882 
    targetPort: 8885
  externalIPs:
    - 192.168.1.99

