apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth-deploy-test
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: oauth-test
  template:
    metadata:
      labels:
        app: oauth-test
    spec:
      imagePullSecrets:
      - name: registry-secret
      containers:
      - name: oauth-backend
       #image: octahub.8lab.cn:5000/99/oauth-backend:v20220617-3
       #image: octahub.8lab.cn:5000/99/oauth-backend:v20220624
        image: octahub.8lab.cn:5000/99/oauth-backend:v2208261733
        volumeMounts:
        - mountPath: "/usr/local/oauth/config/config.yaml"
          subPath: config.yaml
          name: oauth-cm
        ports:
        - containerPort: 9001
          protocol: TCP
        resources:
          limits:
            cpu: 512m
            memory: 256Mi
          requests:
            cpu: 512m
            memory: 256Mi
      - name: oauth-frontend
       #image: octahub.8lab.cn:5000/99/oauth-frontend:v20220617-1
        image: octahub.8lab.cn:5000/99/oauth-frontend:v2208261825
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
        - name: oauth-frontend-cm
          mountPath: /etc/nginx/conf.d/oauth.conf
          subPath: oauth.conf
        - name: oauth-frontend-cm
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: oauth-frontend-tls
          subPath: oauth.crt
          mountPath: /certs/oauth.crt
        - name: oauth-frontend-tls
          subPath: oauth.key
          mountPath: /certs/oauth.key
        resources:
          limits:
            cpu: 512m
            memory: 1Gi
          requests:
            cpu: 512m
            memory: 256Mi
      restartPolicy: Always
      volumes:
      - name: oauth-cm 
        configMap:
          name: oauth-cm-test
      - name: oauth-frontend-cm
        configMap:
          name: oauth-frontend-test-cm
      - name: oauth-frontend-tls
        secret:
          secretName: oauth-frontend-test-tls
