apiVersion: v1
kind: ConfigMap
metadata:
  name: oauth-frontend-test-cm
  namespace: default
data:
  nginx.conf: |
    user  trust trust;
    worker_processes auto;
    #worker_cpu_affinity auto;
    worker_rlimit_nofile 102400;
    
    error_log   /data/logs/nginx/nginx-error.log crit;
    pid         /var/log/nginx/nginx.pid;
    
    events {
        use                epoll;
        multi_accept       on;
        worker_connections 51200;
    }
    
    # load modules compiled as Dynamic Shared Object (DSO)
    #
    #dso {
    #    load ngx_http_fastcgi_module.so;
    #    load ngx_http_rewrite_module.so;
    #}
    
    http {
        include       mime.types;
        default_type  application/octet-stream;
        charset       utf-8;
    
        map $remote_addr $old_remote_addr{
                default $remote_addr;
        }
    
        #set_real_ip_from   172.16.0.0/16;
        real_ip_header     X-Forwarded-For;
    
    
        log_format  main  '$remote_addr|"$http_x_forwarded_for"|"$old_remote_addr"|[$time_local]|"$request"|'
                                  '$status|$body_bytes_sent|$bytes_sent|$request_time|$request_length|'
                                  '"$sent_http_content_type"|"$http_referer"|"$http_user_agent"|$http_host|$sent_http_cached|$http_RequestId';
    
        access_log  /data/logs/nginx/nginx-access.log  main;
    
        sendfile       on;
        tcp_nopush     on;
        tcp_nodelay    on;
    
        #server_tag     off;
        #server_info    off;
        #server_tokens  off;
    
        server_names_hash_bucket_size 128;
        client_header_buffer_size 32k;
        large_client_header_buffers 4 64k;
        client_max_body_size 50m;
        client_body_buffer_size 8m;
    
        keepalive_timeout  10;
    
        gzip  on;
        gzip_min_length 1k;
        gzip_buffers 4 16k;
        gzip_http_version 1.1;
        gzip_comp_level 2;
        gzip_types text/plain application/x-javascript text/css application/xml;
        gzip_vary on;
    
        limit_req_zone $http_x_forwarded_for zone=openapi:10m rate=60r/m;
    
        include     /etc/nginx/conf.d/*.conf;
    
    }
  oauth.conf: | 
    server {
      listen         8080;
      server_name    .*;
      charset UTF-8;
      underscores_in_headers  on;
      #access_log      /data/logs/myweb_access.log;
      error_log       /data/logs/nginx/error_fuzhou.log;
        ssl on;
        ssl_certificate /certs/oauth.crt;
        ssl_certificate_key /certs/oauth.key;
        ssl_session_timeout 5m;
        ssl_protocols TLSv1.1 TLSv1.2; #按照这个协议配置
        ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:HIGH:!aNULL:!MD5:!RC4:!DHE;#按照这个套件配置
        ssl_prefer_server_ciphers on;
    

      root        /usr/local/oauth/dist/;
            client_max_body_size 75M;
    
            location /api {
                proxy_pass https://127.0.0.1:9001;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            }

          location / {
            try_files $uri $uri/ /index.html;
            index /index.html;
          }
        }

