kind: Service
apiVersion: v1
metadata:
  name: oauth-test-svc
  namespace: default
spec:
  ports:
  - port: 8084
    targetPort: 8080
  selector:
    app: oauth-test
  externalIPs:
  - 192.168.1.79
  - 101.251.205.213
