apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ops-rb
  namespace: osotestwk-osotest  #{NAMESPACE}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ops-cr
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: ops
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ops-rb
  namespace: logging
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ops-cr
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: ops

