apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: oscro-v2
  name: sourceserver-sts
  labels:
    app.oscro.io/name: sourceserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app.oscro.io/name: sourceserver
  template:
    spec:
      volumes:
        - name: sourceserver-cm
          configMap:
            name: sourceserver-cm
      containers:
        - name: sourceserver
          image: octahub.8lab.cn:5000/oscro/octa-sourceserver:v2401101338 
          resources:
            limits:
              cpu: 100m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 500Mi
          volumeMounts:
            - name: sourceserver-cm
              subPath: config.ini
              mountPath: /usr/local/server/src/config/config.ini
            - name: log-data 
              mountPath: /data/oscro-v2/logs
      imagePullSecrets:
        - name: registry-secret
    metadata:
      labels:
        app.oscro.io/name: sourceserver
  volumeClaimTemplates:
    - spec:
        resources:
          requests:
            storage: 200Mi
        accessModes:
          - ReadWriteOnce
      metadata:
        name: log-data
        annotations:
          volume.beta.kubernetes.io/storage-class: csi-rbd-sc
      
