data:
  config.ini: |
    [service]
    Mode = release 
    Port = 10088
    Address = 192.168.1.96
    Name = sourceServer

    [mysql]
    Db = mysql
    DbAddress = 192.168.1.99
    DbPort = 3306
    DbUser = 8lab
    DbPassWord = 8lab
    DbName = oscro
    Charset = utf8mb4

    [consul]
    Address = 192.168.1.97
    Port = 8500
    Token = 83ebd1d0-3682-1cb2-0d64-3a072b030075
    NodeSide = 3


    [log]
    Path = /data/oscro-v2/logs
    SaveDay = 7

    [nsq]
    NsqD = nsqd-service-svc.oscro-v2:4150
    NsqLookupD = nsqlookupd-service-svc.oscro-v2:4161
    ClusterNodePost = 121A9982-0748-w49EB-C443-017FEB60FAB5
    ClusterNodeDelete = 875F2E88-3280-49FB-7006-9E5DF2E636E5
    ClusterNodePatch = B70C8868-517D-6E84-2380-BD0C2C7C74DA
    ClickHousePost = EC4CD7A6-9C17-527F-107B-9F71EC47B676
    ClickHousePatch = 6E3742CC-DF41-461B-8004-3612687D0DC0
    ClickHouseDbCreate = 92E59E77-C72A-E025-4161-465A01B343D8
    ClickHouseDbDelete = ABF2E595-A6D1-61BC-B18D-80592DA33FE2
    ClickHouseDbResetPwk = 33C65AF6-AC59-4ED0-07E7-836B738663C2
    HncCreate = EC51828F-64D1-2D5A-0BAB-888CBC39E6F3
    HncDelete = 032871C2-944A-4422-7C0C-86BEE0CF487A
    NamespaceCreate = 936DC3D2-ED39-F5C9-3EDD-6B95FBDC64BC
    NamespaceDelete =745E2147-2271-779D-BF30-8F4E7549EC36
    NamespacePatch = 6B5243F4-EEA0-16F8-B1CA-5DC9D2F7D6A5
    HarborProjectCreate = 180E99EB-819A-D6B8-6B73-F68F58DA9ADF
    HarborProjectDelete = C3840C38-D3A1-2BAD-9D42-C52288ADFC6A
    HarborSecretPatch = 8C2A11AC-885F-823B-18AC-F7BF4AB6AA3B
    HarborCreate = AAB41771-4C8C-2339-CA3A-7FF05077DF7C
    MdHarborProjectCreate = F067B691-173B-107F-C337-CC69B10CE040

    [auth]
    AuthServerName = authServer
    AuthServerHost = http://192.168.1.96:10081

    [mdHarbor]
    Name = md_harbor
    Schema = http
    Domain = octahub.8lab.cn
    Address = 103.210.160.242
    Port = 5000
    Username = admin
    Password = 7zUdZszglt

kind: ConfigMap
metadata:
  name: sourceserver-cm
  labels:
    app.oscro.io/name: sourceserver
  namespace: oscro-v2
apiVersion: v1
