kind: Service
spec:
  type: ClusterIP
  ports:
    - name: port
      port: 10088
      protocol: TCP
      targetPort: 10088
  selector:
    app.oscro.io/name: sourceserver
  externalIPs:
    - 192.168.1.96
metadata:
  name: sourceserver-svc
  labels:
    app.oscro.io/name: sourceserver
  namespace: oscro-v2
apiVersion: v1
