version: '3'
networks:
  default:
    name: monitor
 
services:
    prometheus:
        image: prom/prometheus
        container_name: monitor_prometheus
        hostname: prometheus
        restart: always
        command:
          - '--config.file=/etc/prometheus/prometheus.yml'
          - '--web.enable-lifecycle'
          - '--storage.tsdb.retention.time=30d'
        volumes:
            - ./prometheus/:/etc/prometheus/
        ports:
            - 10011:9090

    grafana:
        image: grafana/grafana
        container_name: monitor_grafana
        hostname: grafana
        restart: always
        ports:
            - "10012:3000"
        volumes:
            - ./grafana/config/:/etc/grafana/
            - ./grafana/data:/var/lib/grafana
 
    alertmanager:
        image: prom/alertmanager
        container_name: monitor_alertmanager
        hostname: alertmanager
        restart: always
        volumes:
            - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
        ports:
            - 9025:9093
        environment:
          - TZ=Asia/Shanghai
 
    
    dingtalk:
        image: timonwong/prometheus-webhook-dingtalk
        container_name: monitor_dingtalk
        hostname: dingtalk
        restart: always
        volumes:
          - ./dingtalk/config.yml:/etc/prometheus-webhook-dingtalk/config.yml
          - ./dingtalk/dingtalk.tmpl:/opt/dingtalk/template/dingtalk.tmpl

        ports:
          - "9026:8060"

        environment:
          - TZ=Asia/Shanghai

    nodeexporter:
        container_name: monitor_node_exporter
        image: prom/node-exporter
        restart: always
        hostname: nodeExport
        ports:
            - 9023:9100
        volumes:
            - /proc:/host/proc:ro
            - /sys:/host/sys:ro
            - /:/rootfs:ro

    monitor_active_server:
        container_name: monitor_active_server
        image: tusimaservermonitor_monitor-active-server 
        restart: always
        ports:
          - 9024:8000
        volumes:
          - /usr/bin/docker:/usr/bin/docker
          - ./monitor-server/service.yaml:/app/config/service.yaml
          - /var/run/docker.sock:/var/run/docker.sock

    
