kind: Deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app.oscro.io/name: appstatus
  template:
    spec:
      volumes:
        - name: appstatus-cm
          configMap:
            name: appstatus-cm
        - name: appstatus-persistentvolumeclaim-pvc
          persistentVolumeClaim:
            claimName: appstatus-persistentvolumeclaim-pvc
      containers:
        - name: appstatus
          image: octahub.8lab.cn:5000/oscro/appstatus:v2310131458
          resources:
            limits:
              cpu: 100m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 500Mi
          volumeMounts:
            - name: appstatus-cm
              subPath: conf.json
              mountPath: /usr/local/server/src/config/conf.json
            - name: appstatus-persistentvolumeclaim-pvc
              mountPath: /data/oscro-v2/logs
      imagePullSecrets:
        - name: registry-secret
    metadata:
      labels:
        app.oscro.io/name: appstatus
metadata:
  name: appstatus-deployment-deploy
  labels:
    app.oscro.io/name: appstatus
  namespace: oscro-v2
apiVersion: apps/v1
