kind: Service
spec:
  type: ClusterIP
  ports:
    - name: port
      port: 10084
      protocol: TCP
      targetPort: 10084
  selector:
    app.oscro.io/name: appstatus
  externalIPs:
    - 192.168.1.96
metadata:
  name: appstatus-service-svc
  labels:
    app.oscro.io/name: appstatus
  namespace: oscro-v2
apiVersion: v1
