kind: Deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app.oscro.io/name: planserver
  template:
    spec:
      volumes:
        - name: planserver-cm
          configMap:
            name: planserver-cm
        - name: planserver-persistentvolumeclaim-pvc
          persistentVolumeClaim:
            claimName: planserver-persistentvolumeclaim-pvc
      containers:
        - name: planserver
          image: octahub.8lab.cn:5000/oscro/planserver:v2310131638
          # image: octahub.8lab.cn:5000/oscro/octa-planserver-2.2-t:2309112043
          resources:
            limits:
              cpu: 100m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 500Mi
          volumeMounts:
            - name: planserver-cm
              subPath: conf.json
              mountPath: /usr/local/server/src/config/conf.json
            - name: planserver-persistentvolumeclaim-pvc
              mountPath: /data/oscro-v2/logs
      imagePullSecrets:
        - name: registry-secret
    metadata:
      labels:
        app.oscro.io/name: planserver
metadata:
  name: planserver-deployment-deploy
  labels:
    app.oscro.io/name: planserver
  namespace: oscro-v2
apiVersion: apps/v1
