groups:
  - name: 容器服务检测Node39
    rules:
    - alert: zkevm-bridge-ui 
      expr: custom_check_alive_server{zkevm_bridge_ui="stop"} == 0

      for: 1m

      labels:
        severity: P1
        team: "tusima"
        instance: "{{ $labels.instance }}"
        location: "{{ $labels.location }}"

      annotations:
        title: "server zkevm-bridge-ui stop"
        description: "\n- container server 'zkevm-bridge-ui' stop"

    - alert: swap-webapp 
      expr: custom_check_alive_server{swap_webapp="stop"} == 0

      for: 1m

      labels:
        severity: P1
        team: "tusima"
        instance: "{{ $labels.instance }}"
        location: "{{ $labels.location }}"

      annotations:
        title: "server swap-webapp stop"
        description: "\n- container server '' stop"

    - alert: explorer-frontend-l2 
      expr: custom_check_alive_server{explorer_frontend_l2="stop"} == 0

      for: 1m

      labels:
        severity: P1
        team: "tusima"
        instance: "{{ $labels.instance }}"
        location: "{{ $labels.location }}"

      annotations:
        title: "server explorer-frontend-l2 stop"
        description: "\n- container server 'explorer-frontend-l2' stop"
        
    - alert: explorer-backend-l2 
      expr: custom_check_alive_server{explorer_backend_l2="stop"} == 0

      for: 1m

      labels:
        severity: P1
        team: "tusima"
        instance: "{{ $labels.instance }}"
        location: "{{ $labels.location }}"

      annotations:
        title: "server explorer-backend-l2 stop"
        description: "\n- container server 'explorer-backend-l2' stop"

    - alert: explorer-proxy-l2
      expr: custom_check_alive_server{explorer_proxy_l2="stop"} == 0

      for: 1m

      labels:
        severity: P1
        team: "tusima"
        instance: "{{ $labels.instance }}"
        location: "{{ $labels.location }}"

      annotations:
        title: "server explorer-proxy-l2 stop"
        description: "\n- container server 'explorer-proxy-l2' stop"
          
    - alert: node-pg-db
      expr: custom_check_alive_server{node_pg_db="stop"} == 0

      for: 1m

      labels:
        severity: P1
        team: "tusima"
        instance: "{{ $labels.instance }}"
        location: "{{ $labels.location }}"

      annotations:
        title: "server node-pg-db stop"
        description: "\n- container server 'node-pg-db' stop"


    - alert: zkevm-prover
      expr: custom_check_alive_server{zkevm_prover="stop"} == 0

      for: 1m

      labels:
        severity: P1
        team: "tusima"
        instance: "{{ $labels.instance }}"
        location: "{{ $labels.location }}"

      annotations:
        title: "server zkevm-prover stop"
        description: "\n- container server 'zkevm-prover' stop"


    - alert: cdk-near
      expr: custom_check_alive_server{cdk_near="stop"} == 0

      for: 1m

      labels:
        severity: P1
        team: "tusima"
        instance: "{{ $labels.instance }}"
        location: "{{ $labels.location }}"

      annotations:
        title: "server cdk-near stop"
        description: "\n- container server 'cdk-near' stop"


    - alert: explorer-stats-l2
      expr: custom_check_alive_server{explorer_stats_l2="stop"} == 0

      for: 1m

      labels:
        severity: P1
        team: "tusima"
        instance: "{{ $labels.instance }}"
        location: "{{ $labels.location }}"

      annotations:
        title: "server explorer-stats-l2 stop"
        description: "\n- container server 'explorer-stats-l2' stop"

    - alert: explorer-stats-db-l2
      expr: custom_check_alive_server{explorer_stats_db_l2="stop"} == 0

      for: 1m

      labels:
        severity: P1
        team: "tusima"
        instance: "{{ $labels.instance }}"
        location: "{{ $labels.location }}"

      annotations:
        title: "server explorer-stats-db-l2 stop"
        description: "\n- container server 'explorer-stats-db-l2' stop"

    - alert: explorer-backend-l2-db
      expr: custom_check_alive_server{explorer_backend_l2_db="stop"} == 0

      for: 1m

      labels:
        severity: P1
        team: "tusima"
        instance: "{{ $labels.instance }}"
        location: "{{ $labels.location }}"

      annotations:
        title: "server explorer-backend-l2-db stop"
        description: "\n- container server 'explorer-backend-l2-db' stop"
