apiVersion: apps/v1
kind: Deployment
metadata:
  name: harbor-deploy
spec:
  selector:
    matchLabels:
      app: harbor
  replicas: 1
  template:
    metadata:
      labels:
        app: harbor
    spec:
      hostAliases:
      - ip: 111.198.58.84
        hostnames:
        - octahub.8lab.cn 
      imagePullSecrets:
      - name: registry-secret
      initContainers:
      - name: chmod
        image: octahub.8lab.cn:5000/99/busybox:1.28
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        command: ["sh", "-c", "chown -R 1000:1000 /data/harbor"]
        volumeMounts:
          - name: pg-data
            mountPath: /data/harbor/pgsql
          - name: registry-data
            mountPath: /data/harbor/registry
      containers:
      - name: harbor
        image: octahub.8lab.cn:5000/99/harbor:v220429
        imagePullPolicy: IfNotPresent
        #ports:
        #- containerPort: 8080
       #livenessProbe:
       #  tcpSocket:
       #    port: 8080
       #  failureThreshold: 3
       #  initialDelaySeconds: 60
       #  periodSeconds: 10
       #  successThreshold: 1
       #  timeoutSeconds: 30
       #readinessProbe:
       #  tcpSocket:
       #    port: 8080
       #  failureThreshold: 3
       #  initialDelaySeconds: 60
       #  periodSeconds: 10
       #  successThreshold: 1
       #  timeoutSeconds: 30
        resources:
          requests:
            cpu: "1"
            memory: "2G"
          limits:
            cpu: "3"
            memory: "4G"
        volumeMounts:
        - name: pg-data
          mountPath: /data/harbor/pgsql
        - name: registry-data
          mountPath: /data/harbor/registry 
      volumes:
      - name: pg-data
        hostPath:
          path: /data/harbor/pgsql
      - name: registry-data
        hostPath:
          path: /data/harbor/registry
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: harbor
                operator: In
                values:
                - harbor
