apiVersion: apps/v1
kind: Deployment
metadata:
  name: weave-scope-cluster-agent
  labels:
    name: weave-scope-cluster-agent
    app: weave-scope
    weave-cloud-component: scope
    weave-scope-component: cluster-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      name: weave-scope-cluster-agent
      app: weave-scope
      weave-cloud-component: scope
      weave-scope-component: cluster-agent
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        name: weave-scope-cluster-agent
        app: weave-scope
        weave-cloud-component: scope
        weave-scope-component: cluster-agent
    spec:
      imagePullSecrets:
      - name: registry-secret
      containers:
        - name: scope-cluster-agent
          args:
            - --mode=probe
            - --weave=false
            - --probe-only
            - --probe.kubernetes.role=cluster
            - --probe.no-controls=false
            - weave-scope-app:4040
          env:
          - name: CHECKPOINT_DISABLE
            value: "true"
          image: octahub.8lab.cn:5000/99/weavescope:1.13.2
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          volumeMounts:
            - name: scope-plugins
              mountPath: /var/run/scope/plugins
      serviceAccountName: weave-scope
      volumes:
        - name: scope-plugins
          hostPath:
            path: /var/run/scope/plugins
