apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: weave-scope-agent
  labels:
    name: weave-scope-agent
    app: weave-scope
    weave-cloud-component: scope
    weave-scope-component: agent
spec:
  minReadySeconds: 5
  selector:
    matchLabels:
      app: weave-scope
  template:
    metadata:
      labels:
        name: weave-scope-agent
        app: weave-scope
        weave-cloud-component: scope
        weave-scope-component: agent
    spec:
      imagePullSecrets:
      - name: registry-secret
      containers:
        - name: scope-agent
         #command:
         #- sh
         #- -c
         #args:
         #- sleep 3600
          args:
            - --mode=probe
            - --weave=false
            - --probe-only
            - --probe.kubernetes.role=host
            - --probe.docker.bridge=docker0
            - --probe.docker=true
            - --probe.proc.spy=true
            - --probe.no-controls=false
            - weave-scope-app:4040
          env:
          - name: SCOPE_HOSTNAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: CHECKPOINT_DISABLE
            value: "true"
          image: octahub.8lab.cn:5000/99/weavescope:1.13.2
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          securityContext:
            privileged: true
          volumeMounts:
            - name: docker-socket
              mountPath: /var/run/docker.sock
              readOnly: true
            - name: scope-plugins
              mountPath: /var/run/scope/plugins
            - name: sys-kernel-debug
              mountPath: /sys/kernel/debug
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      hostPID: true
      tolerations:
        - effect: NoSchedule
          operator: Exists
      volumes:
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
        - name: scope-plugins
          hostPath:
            path: /var/run/scope/plugins
        - name: sys-kernel-debug
          hostPath:
            path: /sys/kernel/debug
      #securityContext:
      #  runAsUser: 0
      #  fsGroup: 0
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
