kind: Service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 4151
      protocol: TCP
      targetPort: 4151
    - name: tcp
      port: 4150
      protocol: TCP
      targetPort: 4150
  selector:
    app.oscro.io/name: nsqd
  externalIPs: []
metadata:
  name: nsqd-service-svc
  labels:
    app.oscro.io/name: nsqd
  namespace: oscro-v2
apiVersion: v1
