kind: Deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app.oscro.io/name: nsqd
  template:
    spec:
      volumes:
        - name: nsqd-persistentvolumeclaim-pvc
          persistentVolumeClaim:
            claimName: nsqd-persistentvolumeclaim-pvc
      containers:
        - env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          args:
            - nsqd
            - '--broadcast-address=$(POD_IP)'
            - '--lookupd-tcp-address=nsqlookupd-service-svc:4160'
            - '--data-path=/data/'
          name: nsq
          image: octahub.8lab.cn:5000/oscro/nsq:v1.2.1
          resources:
            limits:
              cpu: 100m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 500Mi
          volumeMounts:
            - name: nsqd-persistentvolumeclaim-pvc
              mountPath: /data
          imagePullPolicy: Always
      restartPolicy: Always
      imagePullSecrets:
        - name: registry-secret
    metadata:
      labels:
        app.oscro.io/name: nsqd
metadata:
  name: nsqd-deployment-deploy
  labels:
    app.oscro.io/name: nsqd
  namespace: oscro-v2
apiVersion: apps/v1
