apiVersion: v1
kind: Service
metadata:
  name: main-server-svc
  namespace: default 
  labels:
    app: main-server 
spec:
  selector:
    app: main-server
  ports:
  - name: web
    port: 8887
    targetPort: 8080
  externalIPs:
    - 192.168.1.99 

