apiVersion: v1
kind: ConfigMap
metadata:
  name: main-server-cm
  namespace: default
  labels:
    app: main-server
data:
  config.json: |
    {
      "DB": {
        "dbHost": "mysql-service.default",
        "dbPort": 3306,
        "dbName": "mainportal-0820",
        "dbUser": "8lab",
        "dbPasswd": "8lab"
      },
      "Jwe": {
        "expTime": 9000,
        "currencyRsa": "lib/auth/currencyRsa",
        "oauthRsa": "lib/auth/oauthRsa"
      },
      "Oauth2Conf": {
        "oauthServerAddress": "https://192.168.1.98:8083",
        "clientID": "k9mqw4kv121jwvpzq4ne",
        "clientSecret": "paqhfxceqaicioch3zkk5g941n8uuaolalp5vshq",
        "redirectUrl": "http://192.168.1.99:8887/oauth",
        "response_type": "code",
        "scope": "all",
        "state": "octa8lab",
        "authUrl": "/login",
        "tokenUrl": "/api/oauth/token",
        "userUrl": "/api/oauth/user"
      },
      "Harbor": {
        "domain": "octahub.8lab.cn:5000",
        "userName": "admin",
        "passWd": "T@m$t^SP$w0rd_8LaB"
      },
      "timeout": 15,
      "use_oauth_auth": "Y",
      "logPath": "/var/log/mainPortalLog/",
      "Develop": 0
    }
  front.conf: |
    map $http_upgrade $connection_upgrade {
        default upgrade;
        '' close;
    }
    server {
            listen         8080;
            server_name    .*;
            charset UTF-8;
            access_log      /data/logs/nginx/access.log;
            error_log       /data/logs/nginx/error.log;

            client_max_body_size 75M;
            gzip on;
            gzip_comp_level 3;
            gzip_types application/javascript image/png video/mp4;
            gzip_vary on;

            root        /usr/local/octa_optmain_porta_frontend/dist/;
            location / {
              try_files $uri $uri/ /index.html;
              index /index.html;
            }


            location ~ ^/api {
              proxy_set_header Upgrade $http_upgrade;
              proxy_set_header Connection "$connection_upgrade";
              proxy_set_header Host $http_host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              if ($arg_opt_address){
                      proxy_pass http://$arg_opt_address:$arg_opt_port;
                      break;
               }
               uwsgi_pass 127.0.0.1:9005;
               include uwsgi_params;

            }
    }
  uwsgi.ini: |
    [uwsgi]
    chdir=/usr/local/mainPortal
    module=mainPortal.wsgi:application
    processes = 8
    threads = 64
    listen = 2048
    socket=0.0.0.0:9005
    vacuum = true
    max-requests = 1000
    socket-timeout = 20
    buffer-size = 32768
    harakiri = 30
    harakiri-verbose = true
    log-maxsize = 50000000
    pidfile=/usr/local/mainPortal/uwsgi.pid
    logto=/var/log/mainPortalLog/uwsgi.log
    uid=ubuntu
    gid=ubuntu
    master=true
    vacuum=true
    enable-threads=true
    buffer-size=65536
