kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: main-portal-cr
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["pods","pods/log","namespace"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["*"]
  verbs: ["get","patch","update"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: main-portal-crb
subjects:
- kind: ServiceAccount
  name: main-portal-sa
  namespace: default 
roleRef:
  kind: ClusterRole
  name: main-portal-cr
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: main-portal-sa
  namespace: default
