// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.9
// source: pb/Prod.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type T2Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *T2Request) Reset() {
	*x = T2Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_Prod_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *T2Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*T2Request) ProtoMessage() {}

func (x *T2Request) ProtoReflect() protoreflect.Message {
	mi := &file_pb_Prod_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use T2Request.ProtoReflect.Descriptor instead.
func (*T2Request) Descriptor() ([]byte, []int) {
	return file_pb_Prod_proto_rawDescGZIP(), []int{0}
}

func (x *T2Request) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type T2Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string      `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Detail *RespDetail `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
}

func (x *T2Response) Reset() {
	*x = T2Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_Prod_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *T2Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*T2Response) ProtoMessage() {}

func (x *T2Response) ProtoReflect() protoreflect.Message {
	mi := &file_pb_Prod_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use T2Response.ProtoReflect.Descriptor instead.
func (*T2Response) Descriptor() ([]byte, []int) {
	return file_pb_Prod_proto_rawDescGZIP(), []int{1}
}

func (x *T2Response) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *T2Response) GetDetail() *RespDetail {
	if x != nil {
		return x.Detail
	}
	return nil
}

type RespDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Age     string `protobuf:"bytes,1,opt,name=age,proto3" json:"age,omitempty"`
	Address string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *RespDetail) Reset() {
	*x = RespDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_Prod_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespDetail) ProtoMessage() {}

func (x *RespDetail) ProtoReflect() protoreflect.Message {
	mi := &file_pb_Prod_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespDetail.ProtoReflect.Descriptor instead.
func (*RespDetail) Descriptor() ([]byte, []int) {
	return file_pb_Prod_proto_rawDescGZIP(), []int{2}
}

func (x *RespDetail) GetAge() string {
	if x != nil {
		return x.Age
	}
	return ""
}

func (x *RespDetail) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

var File_pb_Prod_proto protoreflect.FileDescriptor

var file_pb_Prod_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x70, 0x62, 0x2f, 0x50, 0x72, 0x6f, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x02, 0x70, 0x62, 0x22, 0x1f, 0x0a, 0x09, 0x54, 0x32, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x22, 0x48, 0x0a, 0x0a, 0x54, 0x32, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x26, 0x0a, 0x06, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x73, 0x70,
	0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x06, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x22, 0x38,
	0x0a, 0x0a, 0x52, 0x65, 0x73, 0x70, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x10, 0x0a, 0x03,
	0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x61, 0x67, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x32, 0x34, 0x0a, 0x09, 0x54, 0x32, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x27, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x4d, 0x73, 0x67, 0x12,
	0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x32, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0e,
	0x2e, 0x70, 0x62, 0x2e, 0x54, 0x32, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x06,
	0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_Prod_proto_rawDescOnce sync.Once
	file_pb_Prod_proto_rawDescData = file_pb_Prod_proto_rawDesc
)

func file_pb_Prod_proto_rawDescGZIP() []byte {
	file_pb_Prod_proto_rawDescOnce.Do(func() {
		file_pb_Prod_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_Prod_proto_rawDescData)
	})
	return file_pb_Prod_proto_rawDescData
}

var file_pb_Prod_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pb_Prod_proto_goTypes = []interface{}{
	(*T2Request)(nil),  // 0: pb.T2Request
	(*T2Response)(nil), // 1: pb.T2Response
	(*RespDetail)(nil), // 2: pb.RespDetail
}
var file_pb_Prod_proto_depIdxs = []int32{
	2, // 0: pb.T2Response.detail:type_name -> pb.RespDetail
	0, // 1: pb.T2Service.GetMsg:input_type -> pb.T2Request
	1, // 2: pb.T2Service.GetMsg:output_type -> pb.T2Response
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pb_Prod_proto_init() }
func file_pb_Prod_proto_init() {
	if File_pb_Prod_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_Prod_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*T2Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_Prod_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*T2Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_Prod_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_Prod_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_Prod_proto_goTypes,
		DependencyIndexes: file_pb_Prod_proto_depIdxs,
		MessageInfos:      file_pb_Prod_proto_msgTypes,
	}.Build()
	File_pb_Prod_proto = out.File
	file_pb_Prod_proto_rawDesc = nil
	file_pb_Prod_proto_goTypes = nil
	file_pb_Prod_proto_depIdxs = nil
}
