apiVersion: app.oscro.io/v1beta1
kind: Application
metadata:
  finalizers:
    - foregroundDeletion
  name: tabixweb
  namespace: oscro-v2
spec:
  addOwnerRef: true
  componentKinds:
    - group: tekton.dev
      kind: PipelineRun
    - group: v1
      kind: Service
    - group: apps
      kind: Deployment
    - group: v1
      kind: ConfigMap
  selector:
    matchLabels:
      app.oscro.io/name: tabixweb
