apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.oscro.io/name: tabixweb
  name: tabixweb-deployment-deploy
  namespace: oscro-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app.oscro.io/name: tabixweb
  template:
    metadata:
      labels:
        app.oscro.io/name: tabixweb
    spec:
      containers:
        - image: octahub.8lab.cn:5000/oscro/tabixweb:v2310131718
          name: oscroweb
          resources:
            limits:
              cpu: 100m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 500Mi
          volumeMounts:
            - mountPath: /etc/nginx/conf.d/front.conf
              name: tabixweb-cm
              subPath: front.conf
      imagePullSecrets:
        - name: registry-secret
      volumes:
        - configMap:
            name: tabixweb-cm
          name: tabixweb-cm
