apiVersion: v1
data:
  front.conf: |
    map $http_upgrade $connection_upgrade {
        default upgrade;
        '' close;
    }
    server {
            listen         8080;
            server_name    .*;
            charset UTF-8;
            access_log      /data/logs/nginx/access.log;
            error_log       /data/logs/nginx/error.log;

            client_max_body_size 75M;
            gzip on;
            gzip_comp_level 3;
            gzip_types application/javascript image/png video/mp4;
            gzip_vary on;

            root        /usr/local/tabix/dist/;
            location / {
             try_files $uri $uri/ /index.html;
             index /index.html;
            }

    }
kind: ConfigMap
metadata:
  labels:
    app.oscro.io/name: tabixweb
  name: tabixweb-cm
  namespace: oscro-v2
