kind: Service
spec:
  type: ClusterIP
  ports:
    - name: port
      port: 10085
      protocol: TCP
      targetPort: 10085
  selector:
    app.oscro.io/name: harborserver
  externalIPs:
    - 192.168.1.96
metadata:
  name: harborserver-service-svc
  labels:
    app.oscro.io/name: harborserver
  namespace: oscro-v2
apiVersion: v1
