apiVersion: v1
kind: Service
metadata:
  name: ciserver-svc
  namespace: default 
  labels:
    app: ciserver 
spec:
  selector:
    app: ciserver
  ports:
  - name: web
    port: 9002
    targetPort: 9002
  externalIPs:
    - 192.168.1.79

