apiVersion: v1
kind: ConfigMap
metadata:
  name: ciserver-cm
  namespace: default
  labels:
    app: ciserver
data:
  .gitconfig: |
    [user]
        name = zhangyy27
        email = 1149855229@qq.com
    [http]
            proxy = socks5://192.168.1.65:1080
    [https]
            proxy = socks5://192.168.1.65:1080

  config.json: |
    {
      "RepoInfo": {
        "Path": "/data/repo-data/",
        "Domain": "octahub.8lab.cn:5000",
        "User": "admin",
        "PassWD": "7yi8HQlRtJ",
        "YamlFileFolder": "",
        "YamlFilePath": ""
      },
      "DBInfo": {
        "dbHost": "mysql-service.default",
        "dbPort": 3306,
        "dbUser": "8lab",
        "dbPasswd": "8lab",
        "dbName": "mainportal-0820"
      },
      "Harbor": {
        "domain": "octahub.8lab.cn:5000",
        "userName": "admin",
        "passWd": "T@m$t^SP$w0rd_8LaB"
      },
      "BaseImage": {
        "python": {
          "base/cicd-python": [
            "v20220418"
          ],
          "base/cicd-python36": [
            "v20220419"
          ]
 
        },
        "go": {
          "base/cicd-go": [
            "v20220418"
          ]
        },
        "npm": {
          "base/cicd-npm": [
            "v220831"
          ]
        }
      },
      "UpLink": {
        "Server": "http://192.168.1.98:9984",
        "Url": "/api/v1/transactions?asset_id="
      },
      "Jwe": {
        "expTime": 9000,
        "priKey": "auth/oauthRsa"
      },
      "Env": "local99",
      "LogPath": "/var/log/ciServerLog/",
      "UpLinkServer": "http://192.168.1.98:9984/api/v1/transactions?asset_id=",
      "GrpcServer": "101.251.211.206:10082",
      "PriKeyPath": "auth/oauthRsa",
      "timeOut": 15,
      "podServer": ["192.168.1.99","192.168.1.98"]
    }
  uwsgi.ini: |
    [uwsgi]
    chdir=/usr/local/ciServer
    module=ciServer.wsgi:application
    workers=4
    http=0.0.0.0:9002
    pidfile=/usr/local/ciServer/ciServer.pid
    logto=/var/log/ciServerLog/uwsgi.log
    uid=ubuntu
    gid=ubuntu
    master=true
    vacuum=true
    enable-threads=true
    buffer-size=65536
